In [15]:
import pandas as pd

df = pd.read_csv("creditcard.csv")

In [16]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [17]:
normal = df[df["Class"] == 0]
fraud = df[df["Class"] == 1]

In [18]:
context_normal = normal.sample(n=90, random_state=42)
context_fraud = fraud.sample(n=10, random_state=42)

In [19]:
context = pd.concat(
    [context_normal, context_fraud]
)

In [20]:
remaining = df.drop(context.index)

In [21]:
test = remaining.sample(n=10, random_state=123).copy()

In [22]:
test

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
236309,148756.0,1.585458,-1.682603,-1.778289,0.014642,-0.642479,-0.548470,0.092731,-0.361649,-0.369115,...,-0.084125,-0.323171,-0.236148,-0.693400,-0.042408,0.467900,-0.096325,-0.011158,332.20,0
50906,44701.0,1.272282,-0.824263,1.060697,-0.671989,-1.635468,-0.528977,-1.139163,0.102412,-0.571754,...,0.452693,1.139361,-0.101525,0.574173,0.338667,-0.079976,0.025188,0.020391,34.99,0
73315,55082.0,-0.504602,1.044723,2.108899,0.472115,0.627370,-0.408675,1.311591,-0.479766,-0.889177,...,-0.157735,-0.245449,-0.038342,0.405436,-0.605491,0.467795,-0.431732,-0.326206,7.01,0
138686,82792.0,1.234444,-0.891419,0.729484,-0.383660,-1.192480,0.163965,-0.830614,0.071604,-0.381957,...,-0.461482,-0.614560,-0.058649,0.095923,0.317799,1.060372,-0.025887,0.005752,50.25,0
96096,65605.0,-1.091409,-0.051472,1.316516,-2.164792,-0.269581,-0.755309,0.131037,-0.014965,-1.250110,...,-0.429542,-0.776284,0.053085,0.019525,-0.240668,1.163885,-0.019338,0.161641,22.69,0
5665,5921.0,-2.229818,2.247262,0.616172,-0.075552,-0.696383,-0.307728,-0.320726,0.904834,1.078978,...,-0.247700,-0.621363,0.188980,0.125309,-0.186595,0.013333,-0.081032,0.147845,10.48,0
250210,154783.0,-4.318329,3.382047,-2.401266,-0.849128,-1.174665,-1.558351,-0.564308,1.576343,1.074365,...,-0.299760,-0.363344,0.635505,0.032048,-0.283393,0.144945,0.037258,0.196183,3.01,0
271595,164650.0,2.097339,-0.116883,-1.654908,-0.079319,0.775584,0.249168,0.016021,-0.020777,0.276557,...,-0.303883,-0.784802,0.230648,-0.399314,-0.165098,0.215319,-0.074990,-0.073688,1.98,0
49395,44039.0,1.307641,-0.616560,0.223056,-0.487294,-0.628007,0.170265,-0.659089,0.086712,-0.942385,...,-0.589148,-1.396309,0.043201,-0.881226,0.103080,0.260795,-0.016688,0.011978,49.99,0
101411,67825.0,1.185758,0.649432,0.567597,2.497431,-0.053612,-0.566781,0.261369,-0.214955,-0.914454,...,0.135471,0.418392,-0.141025,0.422530,0.675762,0.142230,-0.009981,0.021572,11.35,0

In [8]:
test["Class"] = "[PREDICT]"

In [9]:
data = pd.concat(
    [context, test],
    ignore_index=True
)

In [12]:
data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,82450.0,1.314539,0.590643,-0.666593,0.716564,0.301978,-1.125467,0.388881,-0.288390,-0.132137,...,-0.170307,-0.429655,-0.141341,-0.200195,0.639491,0.399476,-0.034321,0.031692,0.76,0
1,50554.0,-0.798672,1.185093,0.904547,0.694584,0.219041,-0.319295,0.495236,0.139269,-0.760214,...,0.202287,0.578699,-0.092245,0.013723,-0.246466,-0.380057,-0.396030,-0.112901,4.18,0
2,55125.0,-0.391128,-0.245540,1.122074,-1.308725,-0.639891,0.008678,-0.701304,-0.027315,-2.628854,...,-0.133485,0.117403,-0.191748,-0.488642,-0.309774,0.008100,0.163716,0.239582,15.00,0
3,116572.0,-0.060302,1.065093,-0.987421,-0.029567,0.176376,-1.348539,0.775644,0.134843,-0.149734,...,0.355576,0.907570,-0.018454,-0.126269,-0.339923,-0.150285,-0.023634,0.042330,57.00,0
4,90434.0,1.848433,0.373364,0.269272,3.866438,0.088062,0.970447,-0.721945,0.235983,0.683491,...,0.103563,0.620954,0.197077,0.692392,-0.206530,-0.021328,-0.019823,-0.042682,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,5921.0,-2.229818,2.247262,0.616172,-0.075552,-0.696383,-0.307728,-0.320726,0.904834,1.078978,...,-0.247700,-0.621363,0.188980,0.125309,-0.186595,0.013333,-0.081032,0.147845,10.48,[PREDICT]
106,154783.0,-4.318329,3.382047,-2.401266,-0.849128,-1.174665,-1.558351,-0.564308,1.576343,1.074365,...,-0.299760,-0.363344,0.635505,0.032048,-0.283393,0.144945,0.037258,0.196183,3.01,[PREDICT]
107,164650.0,2.097339,-0.116883,-1.654908,-0.079319,0.775584,0.249168,0.016021,-0.020777,0.276557,...,-0.303883,-0.784802,0.230648,-0.399314,-0.165098,0.215319,-0.074990,-0.073688,1.98,[PREDICT]
108,44039.0,1.307641,-0.616560,0.223056,-0.487294,-0.628007,0.170265,-0.659089,0.086712,-0.942385,...,-0.589148,-1.396309,0.043201,-0.881226,0.103080,0.260795,-0.016688,0.011978,49.99,[PREDICT]
109,67825.0,1.185758,0.649432,0.567597,2.497431,-0.053612,-0.566781,0.261369,-0.214955,-0.914454,...,0.135471,0.418392,-0.141025,0.422530,0.675762,0.142230,-0.009981,0.021572,11.35,[PREDICT]

In [13]:
data.to_csv("data_balanced_sample.csv", index=False)