In [1]:
import pandas as pd

df = pd.read_csv("../../creditcard.csv")

In [2]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [3]:
len(df)

284807

In [4]:
normal = df[df["Class"] == 0]
fraud = df[df["Class"] == 1]

In [5]:
len(normal)

284315

In [6]:
len(fraud)

492

In [7]:
context_normal = normal.sample(n=1800, random_state=42)
context_fraud = fraud.sample(n=50, random_state=42)

In [8]:
context = pd.concat(
    [context_normal, context_fraud]
)

In [9]:
remaining = df.drop(context.index)

In [10]:
context = context.sample(frac=1, random_state=42).reset_index(drop=True)

In [11]:
remaining_normal = remaining[remaining["Class"] == 0]
remaining_fraud = remaining[remaining["Class"] == 1]

In [12]:
normal_test = remaining_normal.sample(n=150, random_state=123)
fraud_test = remaining_fraud.sample(n=30, random_state=123)

In [13]:
test = pd.concat(
    [normal_test, fraud_test]
).sample(frac=1, random_state=42)

In [14]:
test["ActualClass"] = test["Class"]

In [15]:
test["Class"] = "[PREDICT]"

In [16]:
test.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,ActualClass
11725,20049.0,-0.945149,1.068939,1.546351,1.755647,1.358144,-1.102677,0.925867,-0.237994,-0.315663,...,-0.119309,-0.211618,0.304047,0.346450,-0.112368,-0.016076,0.099622,2.50,[PREDICT],0
222058,142801.0,1.999711,0.124873,-1.900434,0.357359,0.425920,-0.980982,0.215022,-0.245132,0.312602,...,0.776486,-0.104761,-0.471002,0.276093,-0.099838,-0.007820,-0.038677,24.95,[PREDICT],0
8615,11629.0,-3.891192,7.098916,-11.426467,8.607557,-2.065706,-2.985288,-8.138589,2.973928,-6.272790,...,-0.189709,-0.508629,-1.189308,1.188536,0.605242,1.881529,0.875260,1.00,[PREDICT],1
215445,140074.0,2.197151,-1.284177,-2.705352,-1.569228,-0.126263,-1.285567,0.179146,-0.646494,-2.143848,...,0.792081,-0.222737,0.671034,0.637134,0.266021,-0.092257,-0.062815,126.80,[PREDICT],0
135952,81480.0,-0.615511,1.089944,1.412684,0.446489,0.070351,-0.671488,0.484245,0.030471,-0.386319,...,-0.398363,0.072860,0.349784,-0.660061,0.133660,0.250923,0.210383,1.79,[PREDICT],0

In [17]:
data = pd.concat(
    [context, test],
    ignore_index=True
)

In [18]:
data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,ActualClass
0,167834.0,-0.423494,-0.344245,1.684584,-2.456217,-0.895188,2.034611,-2.286392,-1.915239,2.491759,...,0.735375,-0.536248,-0.291585,1.746961,0.129987,0.066741,0.154193,0.22,0,NaN
1,46278.0,-1.221840,1.167173,1.448168,-0.022122,0.007311,0.124128,0.449297,0.235161,0.227386,...,0.642428,-0.106937,0.312141,-0.140409,0.316021,0.145759,-0.191932,3.79,0,NaN
2,99159.0,1.941775,1.190858,-1.911652,4.025149,1.526096,0.152457,0.210495,-0.012158,0.107301,...,-1.513974,0.187627,-1.495846,-0.185813,-0.330235,-0.039248,-0.011221,4.00,0,NaN
3,163016.0,1.973701,-0.437342,-0.466014,0.141490,-0.576589,-0.245589,-0.680047,0.186634,1.340892,...,-0.272780,0.318541,-0.570540,-0.414875,-0.908180,0.047487,-0.045241,1.00,0,NaN
4,71881.0,-0.267610,0.746829,1.571457,-0.286789,-0.024832,-0.433370,0.561358,0.012471,-0.510070,...,-0.253855,-0.105595,0.388791,-0.114627,0.385047,-0.016049,0.007637,4.00,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,43715.0,-0.236253,1.336233,1.577579,2.934260,0.209899,-0.593300,0.796314,-0.149784,-1.695204,...,0.274136,-0.075890,0.711293,-0.349653,0.160616,0.135294,0.155129,10.00,[PREDICT],0.0
2026,124258.0,-0.186633,0.894094,0.141589,-0.617765,0.153931,-1.174490,0.903055,-0.093992,0.434353,...,-0.748866,0.106092,-0.016601,-0.503751,0.148998,0.345646,0.150573,10.99,[PREDICT],0.0
2027,136902.0,-1.037454,-0.634326,1.166372,-4.396227,-0.482524,-0.922018,0.432870,-0.271647,1.207522,...,0.613726,-0.253830,1.103049,0.355476,-0.911879,0.430592,0.055973,92.63,[PREDICT],0.0
2028,134991.0,-0.039155,0.881895,-0.474434,-0.644930,0.438784,0.136351,0.005980,0.614036,-0.100873,...,-0.538046,0.336863,-0.033092,-1.281255,-0.066558,-0.009917,0.071003,25.11,[PREDICT],0.0
2029,64049.0,-0.037948,-0.355606,1.952211,-0.990259,-1.375847,0.052965,-0.516343,0.258514,-0.672035,...,-0.373898,0.201780,0.332187,-0.820594,0.834666,0.029724,0.033809,43.50,[PREDICT],0.0

In [19]:
data.to_csv("data_creditcard_with_class_more_testcases.csv", index=False)

In [20]:
sap_test = test.drop(columns=["ActualClass"])

In [21]:
data_test = pd.concat(
    [context, sap_test],
    ignore_index=True
)

In [22]:
data_test.to_csv(
    "data_test_creditcard_more_testcases.csv",
    index=False
)