In [51]:
import pandas as pd

df = pd.read_csv("../../creditcard.csv")

In [52]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [53]:
len(df)

284807

In [54]:
normal = df[df["Class"] == 0]
fraud = df[df["Class"] == 1]

In [55]:
len(normal)

284315

In [56]:
len(fraud)

492

In [57]:
context_normal = normal.sample(n=1950, random_state=42)
context_fraud = fraud.sample(n=50, random_state=42)

In [58]:
context = pd.concat(
    [context_normal, context_fraud]
)

In [59]:
remaining = df.drop(context.index)

In [60]:
context = context.sample(frac=1, random_state=42).reset_index(drop=True)

In [61]:
remaining_normal = remaining[remaining["Class"] == 0]
remaining_fraud = remaining[remaining["Class"] == 1]

In [62]:
normal_test = remaining_normal.sample(n=30, random_state=123)
fraud_test = remaining_fraud.sample(n=10, random_state=123)

In [63]:
test = pd.concat(
    [normal_test, fraud_test]
).sample(frac=1, random_state=42)

In [64]:
test["ActualClass"] = test["Class"]

In [65]:
test["Class"] = "[PREDICT]"

In [66]:
test.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,ActualClass
261654,160124.0,1.533399,-0.826177,-1.870243,0.689036,-0.338771,-1.178501,0.343105,-0.247829,1.213143,...,-0.664916,-0.007326,-0.155083,-0.218525,-0.107115,-0.059500,0.018202,256.96,[PREDICT],0
136480,81724.0,-1.350654,1.747804,1.155219,0.155125,0.062496,-0.418087,0.599106,0.053903,0.018211,...,-0.556870,0.039746,0.026142,-0.110713,0.222736,0.514367,0.373058,2.28,[PREDICT],0
234407,147963.0,2.120411,-0.913116,-0.473355,-0.607988,-0.699574,0.313040,-1.059947,-0.000921,-0.017568,...,-0.738755,0.354322,0.046030,-0.559948,0.389657,0.004479,-0.028556,29.93,[PREDICT],0
266870,162520.0,-0.940031,0.735888,-0.143082,-3.223992,0.508551,-1.662219,1.103974,-2.071446,1.066983,...,0.093642,-0.120898,0.546879,0.054576,-0.454591,0.301145,-0.016798,24.18,[PREDICT],0
144847,86439.0,2.033087,-0.774613,-0.818585,-0.498218,-1.207113,-1.137887,-1.001913,-0.028368,-0.128427,...,0.939446,0.159977,0.432009,-0.283487,-0.141211,0.019239,-0.015276,29.95,[PREDICT],0

In [67]:
data = pd.concat(
    [context, test],
    ignore_index=True
)

In [68]:
data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V22,V23,V24,V25,V26,V27,V28,Amount,Class,ActualClass
0,125726.0,0.201381,1.167454,-1.063894,-0.044681,0.369790,-1.346828,0.632780,0.086446,-0.217199,...,0.956041,-0.101338,-0.168581,-0.232312,-0.144457,-0.067884,-0.046828,15.70,0,NaN
1,83442.0,1.207869,0.222845,0.066602,1.196308,0.327502,0.316073,0.122808,-0.015837,0.213170,...,-0.141489,-0.184375,-0.733732,0.801658,-0.264073,0.043071,0.010794,16.88,0,NaN
2,149128.0,-0.800117,1.774075,-0.449704,-0.470733,1.255202,-1.313278,1.314603,-0.297820,-0.573497,...,0.805776,-0.535710,-0.115262,0.263462,-0.208850,-0.586967,-0.323186,1.00,0,NaN
3,50496.0,-0.606097,0.857261,1.610462,1.197580,0.348393,0.493555,0.782100,0.108018,-0.536888,...,-0.003882,-0.276597,-0.417394,0.533115,-0.101529,0.088540,0.071364,53.25,0,NaN
4,150263.0,-2.079067,-6.546875,-5.268734,2.590770,-0.379352,0.561994,3.871560,-0.930085,-0.865933,...,-0.114235,-2.253221,-0.174124,0.218804,-0.414875,-0.467482,0.288454,2183.44,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,56255.0,1.167066,0.320273,0.076205,1.206199,0.036503,-0.566867,0.321611,-0.137265,-0.176241,...,0.039286,-0.078352,0.077591,0.634876,-0.314495,0.013149,0.016905,25.80,[PREDICT],0.0
2036,87057.0,2.042990,-0.118762,-1.313449,0.218218,0.242798,-0.502417,0.113318,-0.158220,0.305571,...,-0.469949,0.213657,-0.528473,-0.163695,0.290763,-0.072506,-0.078086,3.66,[PREDICT],0.0
2037,62102.0,0.261375,0.765747,0.984168,0.562839,-0.940607,-0.158272,-1.271422,-2.784200,-0.492692,...,0.207182,0.115109,0.472638,0.107402,1.155959,0.067690,0.260113,7.99,[PREDICT],0.0
2038,147606.0,1.848038,0.189523,-1.748590,1.573249,0.364828,-1.197259,0.574881,-0.348909,0.248616,...,-0.481930,0.113986,-0.159966,0.055326,-0.779052,0.003481,-0.008409,85.16,[PREDICT],0.0
2039,8169.0,0.857321,4.093912,-7.423894,7.380245,0.973366,-2.730762,-1.496497,0.543015,-2.351190,...,0.145400,0.240603,-0.234649,-1.004881,0.435832,0.618324,0.148469,1.00,[PREDICT],1.0

In [69]:
data.to_csv("data_creditcard_with_class_inbalanced.csv", index=False)

In [70]:
sap_test = test.drop(columns=["ActualClass"])

In [71]:
data_test = pd.concat(
    [context, sap_test],
    ignore_index=True
)

In [72]:
data_test.to_csv(
    "data_test_creditcard_inbalanced.csv",
    index=False
)